dist: trusty
sudo: false

language: csharp
solution: WowPacketParser.sln

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1
    - mono: latest
  allow_failures:
    - dotnet: 1.0.1

script: ./scripts/travis-build.sh
